language: c
sudo: false
cache:
  directories:
    - $HOME/lcov-1.13
addons:
  apt:
    packages:
    - gfortran
    - libopenmpi-dev
before_install:
  - |
    if [ ! -f "$HOME/lcov-1.13/usr/local/bin/lcov" ]; then
      wget -O - --no-check-certificate http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz | tar xz && DESTDIR=$HOME/lcov-1.13/ make install -C lcov-1.13
    fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_TESTS=ON -DBUILD_TEST_COVERAGE=ON ..
  - make
  - ./les-test
after_success:
  - $HOME/lcov-1.13/usr/local/bin/lcov -compat-libtool --directory . --capture --output-file coverage.info
  - $HOME/lcov-1.13/usr/local/bin/lcov --remove coverage.info '*/test/google/*' --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X xcode