#!/bin/bash

#$ -M drichte2@nd.edu
#$ -m n
#$ -pe mpi-16 16
#$ -q *@@richter,*@@ivybridge
#$ -N testcase
#$ -j y

cd ~/Research/YIP/testcase/

module load mvapich2/2.1-intel-15.0-mlx
module load intel/15.0
make clean
make

case=testcase
time=0000000
datadir=/scratch365/drichte2/YIP/testcase/

runout=$case.out.$time

imachine=0
echo $imachine > ./mach.file
echo $datadir >> ./mach.file

mpirun -n 4 ./lesmpi.a > $datadir/$runout


